### ISSUE TITLE
the trailer attach and detach doesn't work properly

### ISSUE THREAD

**Issue by wolszhang** [Jumhyn/coms4444-sunshine#2]
[log.txt](https://github.com/Jumhyn/coms4444-sunshine/files/2441020/log.txt)
Here's a detailed log file. I print out all the trailer positions and it is obvious that you should not set trailer to null after passing it to an ArrayList.

**Comment by Jumhyn** [comment]
@wolszhang I have not seen any issues with the trailer behavior. I'll need more info about what the problem is and how to reproduce it in order to debug.

**Comment by Jumhyn** [comment]
I've updated the behavior--let me know if you're still able to reproduce the problem.

**Comment by wolszhang** [comment]
More specifically, in line 273-274

trailers.add(tractor.attachedTrailer);
tractor.attachedTrailer = null;

I think Java is a language that passes by reference. When you modify the original reference, it will be reflected in the ArrayList.

**Comment by wolszhang** [comment]
Here's a simple demo.

StringBuffer sb = new StringBuffer("foo");

List<StringBuffer> list = new ArrayList<StringBuffer>();
list.add(sb);

System.out.println(list);   // prints [foo]
sb.append("bar");

System.out.println(list);   // prints [foobar]

sb = null;

System.out.println(list);   // still prints [foobar]

**Comment by Jumhyn** [comment]
Java passes by value, but all object variables are actually references. So the call to `trailers.add(tractor.attachedTrailer)` passes (by value) the reference to the attached trailer. This reference is stored in the array list. Then, we set `tractor.attachedTrailer` to null. This should not affect the reference stored in the array list. I'll investigate further during class.

**Comment by Jumhyn** [comment]
@wolszhang I'm not seeing any null pointer exceptions. Looks like you are stacking, attaching, and detaching properly.

**Comment by Jumhyn** [comment]
I probably can't stick around for very long after class. Can you submit a minimal example with a simple player that illustrates the null pointer exception? I'll do some more research myself, but would be helpful to have a straightforward example showing the issue. Are you sure you are detaching when you get to the origin? Otherwise it looks like you will get stuck in an `UNLOAD`-`UNSTACK` loop. You can't unstack from an attached trailer. Until we straighten this out, maybe you can use a 'workaround' like g3 does: https://github.com/Jumhyn/coms4444-sunshine/blob/master/sunshine/g3/Player.java

**Comment by Jumhyn** [comment]
Are things working properly now?

**Comment by wolszhang** [comment]
close
